# config.yaml
paths:
  dataset_path: '/home/ubuntu/Dawood/activity_dataset/20231004-activity-all-annotated-tasks'
  annotation_file: '/home/ubuntu/Dawood/activity_dataset/weller_only/20231011_weller_only_combined_valtest_ke_activity_train_avastyle_17.csv'
  checkpoint_path: 'weights/sam_vit_h_4b8939.pth'
  destination_path: '/home/ubuntu/Dawood/Augmentation/Transformed_Data'

model:
  device: 'cuda' # 'cuda', or 'cpu'
  model_type: 'vit_h'

processing:
  video_name: 'activity_nov2022_132138-132538_1'
  frame_numbers: 5

labels:
  k: 9

  label_weights:
    - id: 1
      weight: 10
    - id: 2
      weight: 1
    - id: 3
      weight: 1
    - id: 4
      weight: 1
    - id: 5
      weight: 1
    - id: 6
      weight: 10
    - id: 7
      weight: 1
    - id: 8
      weight: 10
    - id: 9
      weight: 1
    - id: 10
      weight: 1
    - id: 11
      weight: 10
    - id: 12
      weight: 1
    - id: 13
      weight: 1
    - id: 14
      weight: 10
    - id: 15
      weight: 1
    # Add weights for all 15 labels
