# config.yaml
paths:
  dataset_path: ''
  annotation_file: 'sample_annotation.csv'
  checkpoint_path: 'weights/sam_vit_h_4b8939.pth'

model:
  device: 'auto' # 'auto', 'cuda:0', or 'cpu'
  model_type: 'vit_h'

processing:
  video_name: 'activity_nov2022_102526-102556_1'
  frame_numbers: 10

labels:
  label_weights:
    - id: 0
      weight: 0.05
    - id: 1
      weight: 0.1
    - id: 2
      weight: 0.05
    - id: 3
      weight: 0.2
    - id: 4
      weight: 0.02
    - id: 5
      weight: 0.05
    - id: 6
      weight: 0.2
    - id: 7
      weight: 0.1
    - id: 8
      weight: 0.5
    - id: 9
      weight: 0.2
    - id: 10
      weight: 0.1
    - id: 11
      weight: 0.35
    - id: 12
      weight: 0.2
    # Add weights for all 15 labels
